# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: gpouyat <gpouyat@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/09/03 17:12:30 by gpouyat           #+#    #+#              #
#    Updated: 2018/09/03 17:25:09 by gpouyat          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: 
	make -C Colleen

clean:
	make clean -C Colleen

fclean:
	make fclean -C Colleen

re: fclean all

tests:
	make test -C Colleen

.phony: all clean fclean test